[package]
authors = ["xl000 <l_xb@foxmail.com>"]
edition = "2018"
name = "my-redis"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1"
mini-redis = "0.4"
tokio = {version = "1.15", features = ["full"]}
